### PR TITLE
Use offset in BigLog's scanner when reporting next index

### LINKED ISSUE #3: New scanners always return next=0
**Conditions:**

```bash
# create topic
curl -XPOST localhost:7200/bug3
{"ok":true,"message":"topic created"}
# add some data
curl -XPOST localhost:7200/bug3/payload -d "foo"
curl -XPOST localhost:7200/bug3/payload -d "foo"
curl -XPOST localhost:7200/bug3/payload -d "foo"
# create scanner from offset 1
curl -XPOST "localhost:7200/bug3/scanner?from=1"
```

**Expected:**

{"id":"...",**"next":1**,"last":-1,"persistent":false}

**Actual:**

{"id":"...",**"next":0**,"last":-1,"persistent":false}

**Problem:**

The scanner reports to read offset 0 next, despite internally being correctly 1.

### PR DESCRIPTION
**Pull request by cagatay**

### CODE REVIEW

**Comment by cagatay** [comment]
@bictorman could you take a look please? I'm not really sure if `Offset()` always reflects `next - 1` but either this or setting `last` to `from - 1` [here](https://github.com/cagatay/netlog/blob/master/topicscanner.go#L69) should do it. I didn't want to touch `last` since it's initial -1 value is probably also implies scanner's status.

**Comment by bictorman** [comment]
I'm afraid this won't work, since it will **always** return 1 (try it). That's because you can not use `scanner.Offset()` until something has been scanned, actually [this](https://github.com/ninibe/netlog/blob/6c302cdcf1c2bbd9ff74bbaa703a01f91c28dcb9/biglog/scanner.go#L207) should probably return -1 to be correct.

`last` was indeed meant to reflect status, but in hindsight is quite useless.

A possible solution is to add `next` as field of `BLTopicScanner`, set it on the constructor and adjust it to `last + 1 if last >= 0` when someone request info.

An even better solution would be to add `from` as field of `BLTopicScanner`, set `from` in the constructor, then export in the public info `from` and `next` (with `next = from` when `last == -1`). That way the client can not only know if the scanner has been used but also how much.

**Comment by cagatay** [comment]
Would have been nice if I tried that before 😊 Could you check again?

**Comment by bictorman** [comment]
looks good. would you mind wiring a test?

**Comment by cagatay** [comment]
@bictorman done

**Pull request merged**
